### ISSUE TITLE
Typo in README.md for configuration command

### ISSUE THREAD

**Issue by mattaylward** [avvertix/materialicons-laravel-bridge#14]
Hi, I believe it is missing 'Bridge'...

php artisan vendor:publish --provider="MaterialIcons\MaterialIconsBridgeServiceProvider"

...rather than...

php artisan vendor:publish --provider="MaterialIcons\MaterialIconsetServiceProvider"

Thanks for your sofware :-)

**Comment by avvertix** [comment]
Thanks for spotting the typo. The correct command is

```bash
php artisan vendor:publish --provider="MaterialIcons\MaterialIconsBridgeServiceProvider"
```
